### ISSUE TITLE
[EPIC] Streamline/simplify our docker compose 

### ISSUE THREAD

**Issue by jchartrand** [digitalcredentials/dcc-admin-dashboard#16]
The docker compose for the dashboard and related services is a bit clunky and has some things that aren't needed - like the custom network, and the import of the secondary compose file.

Could also look at moving all environment variables from .env files directly into the docker compose for easier evaluation by prospective deployers. They can be easily moved back out to .env files for production deployments.

- [x] #43 
- [x] #44 
- [x] #45 
- [x] #46 
- [x] #47 
- [x] #48 
- [x] #49

**Comment by alexfigtree** [comment]
Kerri asks where/how this can all get documented, in README, etc.

**Comment by alexfigtree** [comment]
Done (complete)
