### ISSUE TITLE
Q&A- Tec: Sending invitation by email

### ISSUE THREAD

**Issue by MyriamLara** [digitalcredentials/dcc-admin-dashboard#28]
Hello! 

Sometimes, when sending the invitation to the students, the dashboard admin is left “Sending”, and we are left with uncertainty because we do not know if the complete process was really done or not. We have observed the above when we send several invitations, since with 1 or 2, the behavior is stable.

Can you please guide us to know where the detail could be?

Below we share evidence through image 1:

![image](https://github.com/digitalcredentials/admin-dashboard/assets/95261927/a9e39c82-d59c-414d-94fb-7e891a28dbc5)

As you can see in image 1, after sending the invitation, it remains “Sending” indefinitely.
With a shipment of approx. 5 students, most of them do not receive the invitation and the console sends the following errors (see images 2 and 3).
 
  
 
Image 2
![image](https://github.com/digitalcredentials/admin-dashboard/assets/95261927/772ce5c4-922d-47c8-8b20-5896d75d6f55)

Image 3
![image](https://github.com/digitalcredentials/admin-dashboard/assets/95261927/5f88b162-aca7-4ef6-9117-f37164532e9a)

**Comment by MyriamLara** [comment]
@jchartrand  add the example csv file as well as the credential and email template, so they can replicate the incident.
[Correo Tec credencial MTY.csv](https://github.com/digitalcredentials/admin-dashboard/files/14423176/Correo.Tec.credencial.MTY.csv)
[plantilla credencial.txt](https://github.com/digitalcredentials/admin-dashboard/files/14423177/plantilla.credencial.txt)

**Comment by kayaelle** [comment]
@MyriamLara - would you be able to try this with Tec de Monterrey smtp or sendmail smtp instead of hotmail? (Javier emailed with this question too)

**Comment by MyriamLara** [comment]
@kayaelle  @jchartrand 
We have tried institutional email and we have had the same problem as with hotmali. There is a certain blocking of transactions by the server, at most it allows us to create 2 requests or in very rare cases 3. Since this is not new and seeing in forums that we are not the only one who has problems with this, we ask about other alternatives. Many developer recommendations recommend using a service like twilio or sendgrid like we are doing. For this reason we do not see the use with the institutional account as feasible, at the time we thought it was problems with the SMTP library that they use to send mail, but when we realized that with Gmail accounts they did come out with a certain configuration creating an authentication for the application In Gmail we were able to make many transactions. We will soon share the solution or steps to follow to do it with Gmail. However, we confirm that with a tec.mx domain, hotmail, outlook or any Microsoft account, there is no more than 1 transaction.

**Comment by kayaelle** [comment]
@MyriamLara - checking in on the status of sending email because i've heard that it is working now. Could you let us know? Also, would love to hear about the solution you found for gmail so we can provide that for others. Thanks!

**Comment by alexfigtree** [comment]
10/17/24: Checking in with Tec to see if this issue has been resolved.

**Comment by alexfigtree** [comment]
11/21/24: Seem to no longer be an issue; closing but can reopen if necessary.
