### ISSUE TITLE
Q&A- Tec: Credential Revocation

### ISSUE THREAD

**Issue by MyriamLara** [digitalcredentials/dcc-admin-dashboard#29]
Another topic that we want to share with you is regarding the revocation of a credential. We share evidence with you (images 4 and 5).

   
Image 4
![image](https://github.com/digitalcredentials/admin-dashboard/assets/95261927/732f9173-09d3-4b21-b9f6-bdda9840215c)
![image](https://github.com/digitalcredentials/admin-dashboard/assets/95261927/8cba7a3b-8f39-413c-b5c8-06a1bb799368)

 
Image 5
![image](https://github.com/digitalcredentials/admin-dashboard/assets/95261927/601a9ce4-5acd-4d7f-8afc-135fdd1054cd)

This error is always triggered when trying to revoke the credential.

**Comment by alexfigtree** [comment]
@MyriamLara What is running on running on port 4008? Could you please show us an error log from the relevant microservice?

**Comment by MyriamLara** [comment]
@alexfigtree  


el contenedor de status en el puerto 4008 esta corriendo pero desde payload no lo alcanza a servidor por fetch: 
y no alcanzamos a hacer ninguna solicitud
![image](https://github.com/digitalcredentials/admin-dashboard/assets/95261927/89d6f52d-32cd-4002-ac2e-f8f83c9bfce5)
![image](https://github.com/digitalcredentials/admin-dashboard/assets/95261927/acd7f40b-eaee-4595-a206-79372585fb56)

 

 

Por lo tanto nuestra propuesta es que mejor usen axios en lugar de fetch
https://www.npmjs.com/package/axios

**Comment by jchartrand** [comment]
@MyriamLara 

Could you show us your docker compose file and any .env files?  Taking out the secret parts of course.

In particular, we want to see what your GitHub configuration for the status list looks like. If you'd rather not post it here in this issue, feel free to email me.

Thanks!

**Comment by AngelOCrz94** [comment]
I attach the versions and environment variables that we use to test the application and we cannot revoke the credential. Can't find the container. I know there is another URL that works, but we don't want to depend on the external service. Solo status of the container. I tried it directly on postaman and the service works. In the payload backend it cannot be linked. You must see some problem with the IP of the containers or ports. Check it. Greetings

[dcc_admin_dashboard.zip](https://github.com/digitalcredentials/dcc-admin-dashboard/files/14891058/dcc_admin_dashboard.zip)

**Comment by kayaelle** [comment]
@jchartrand - would you look into this issue? Could it be related to the version of the software being used?

**Comment by jchartrand** [comment]
@AngelOCrz94 I'm not sure if you meant to include the .env files in the zip? I just see the docker compose file. You could email them to me if that's easier/better.

**Comment by AngelOCrz94** [comment]
@jchartrand  in a moment send you to email this files .env

**Comment by AngelOCrz94** [comment]
I not have shared configuration is own tec. Because no found the revocation.

**Comment by jchartrand** [comment]
@MyriamLara @AngelOCrz94 

Could you try changing the env variable called STATUS_URL to: http://status:4008 (you had it set to http://localhost:4008) and then try revoking a credential again?

Thanks!

**Comment by jchartrand** [comment]
@MyriamLara 

It is still using the local status container service.

http://status:4008 is the address for the service within the docker compose network. It is one of the very cool features of docker compose. The docker compose network knows to resolve that name 'status' to the running local service.

**Comment by alexfigtree** [comment]
@AngelOCrz94 confirms that this issue is resolved during a team meeting on 6/14/24. Closing this issue.
