### ISSUE TITLE
extract logos/images/titles to env vars

### ISSUE THREAD

**Issue by jchartrand** [digitalcredentials/dcc-admin-dashboard#62]
**Is your feature request related to a problem? Please describe.**
Changing logos, images and titles requires code changes and rebuilding.

**Describe the solution you'd like**
Make the dashboard more easily configured by extracting image urls and titles to environment variables.

**Describe alternatives you've considered**
None

**Additional context**
We'll need to identify all images/titles that should be configurable.

**Comment by alexfigtree** [comment]
Issue completed for JFF with new docker images, and tagged commit, updated README, closing ticket
