### ISSUE TITLE
Fix incompatibility between LCW and older admin dashboard versions

### ISSUE THREAD

**Issue by alexfigtree** [digitalcredentials/dcc-admin-dashboard#69]

**Comment by jchartrand** [comment]
I've been working today on some problems with the JFF deployment of the admin dashboard, and have fixed two problems:
their admin dashboard was issuing credentials with a non-uri credential id. I've created a new version of the dashboard that remains issuing VC1 only, but fixes the credential.id problem: [https://hub.docker.com/layers/digitalcredentials/dashboard/0.1.2/images/sha256-ef610[…]d39f401f43fe1881b5e3c47229a4231edd86e8d04b8e7?context=explore](https://hub.docker.com/layers/digitalcredentials/dashboard/0.1.2/images/sha256-ef6101ea971d170d180d39f401f43fe1881b5e3c47229a4231edd86e8d04b8e7?context=explore)

**Comment by jchartrand** [comment]
Also discovered that the new jsonLD libs in the wallet are likely stricter and didn't like a uri for the issuer.image.id that had a space in it. Replacing the space with the escape code fixes that problem.

**Comment by jchartrand** [comment]
So after those two fixes, the JFF issuer is now issuing credentials that I can copy/paste into the latest LCW where they are accepted and verify properly. 

The problem now, however, is that when trying to add the JFF issued credentials to the latest LCW directly using the deeplink, the transaction service (workflow coordinator) returns a 500. My suspicion is that the request from the LCW to the transaction manager includes a didAuth that has been created and signed using the latest VC libs, but the older version of the dashboard on JFF uses older libs that may be balking for some reason at the newer didAuth. 

Investigating...

**Comment by jchartrand** [comment]
This is the didAuth posted from credentialRequest.ts in the LCW:

```
{
  "@context": [
    "https://www.w3.org/ns/credentials/v2",
    "https://w3id.org/security/suites/ed25519-2020/v1"
  ],
  "type": [
    "VerifiablePresentation"
  ],
  "holder": "did:key:z6MknevGC6sQwic5wSgZJ49uoyrK6oK4EuqEtFLHbqzh9tch",
  "proof": {
    "type": "Ed25519Signature2020",
    "created": "2024-10-10T17:24:41Z",
    "verificationMethod": "did:key:z6MknevGC6sQwic5wSgZJ49uoyrK6oK4EuqEtFLHbqzh9tch#z6MknevGC6sQwic5wSgZJ49uoyrK6oK4EuqEtFLHbqzh9tch",
    "proofPurpose": "authentication",
    "challenge": "969d28e4-4f9b-4ac6-842d-af023477dbb3",
    "proofValue": "z2w5DT7DVqYTuVop2jjP1psBHd2AVBW66YhfmXr8rFm3QskbUSNCzxA6WRg91gyB6uNLbuERMgGe7otYHEYCErbMf"
  }
}
```

**Comment by jchartrand** [comment]
So best guess is that the older VC libraries (version 1) in the JFF installation can't deal with the newer VerifiablePresentation (version 2) that the LCW is posting to the workflow coordinator's endpoint.

**Comment by alexfigtree** [comment]
We can close this ticket
