### ISSUE TITLE
batch emails only send first 10

### ISSUE THREAD

**Issue by jchartrand** [digitalcredentials/dcc-admin-dashboard#76]
**Describe the bug**
Only the first ten recipients in a batch are sent a claim email.

**To Reproduce**
1. Create a batch with more than ten credential recipients
2. Send the batch
4. Only the first ten are sent

**Expected behavior**
All recipients in a batch should receive emails

**Additional context**

The problem is very likely here:

https://github.com/digitalcredentials/dcc-admin-dashboard/blob/a59adb251282563dea774ae6fdc5d6f75a983cc0/src/endpoints/sendBatchEmail.ts#L45-L51

i.e., this chunk of code that gets the list of credentials for a given batch when sending out the emails:

```
const data = await payload.find({
        collection: 'credential', // required
        depth: 2,
        where: { ...query }, // pass a `where` query here
        sort: '-title',
        locale: 'en',
    });
```

It seems likely that the 'find' call uses paging by default, with a default result set of 10 per page. So the 'find' call in the sendBatchEmail endpoint (above) is only dealing with the first ten. It would either have to fetch all pages, or it looks like pagination can possibly be turned off, although the payload docs are version 2 and I think the dashboard payload version might be 1, or some combination of 1 and 2. In any case, here is the page from version 2 of the docs, i.e, the bit about setting pagination=false:

https://payloadcms.com/docs/v2/local-api/overview#local-options-available

**Comment by alexfigtree** [comment]
Done and deployed; closing.
